services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true" # Dashboard on :8080
      - "--providers.docker=true" # Read container labels
      - "--providers.file.filename=/certs/certs.yml"
      - "--entrypoints.web.address=:80" # HTTP
      - "--entrypoints.websecure.address=:443" # HTTPS
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs:/certs:ro"
    profiles: ["all"]

  # -------- Authentication Service --------
  authentication:
    container_name: authentication-service
    build:
      context: .
      dockerfile: authentication-service/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
      - "traefik.http.routers.auth.middlewares=cors@file"
    depends_on:
      redis:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - authentication-service/.env
      - .env
    profiles: ["authentication", "all"]

  # -------- Notification Service --------
  notification:
    container_name: notification-service
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notify.rule=Host(`notify.localhost`)"
      - "traefik.http.routers.notify.entrypoints=websecure"
      - "traefik.http.routers.notify.tls=true"
      - "traefik.http.services.notify.loadbalancer.server.port=8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - notification-service/.env
      - .env
    profiles: ["notification", "all"]

  # -------- Extract OTP Service --------
  extract-otp:
    container_name: extract-otp-service
    build:
      context: .
      dockerfile: extract-otp/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.extract.rule=Host(`extract.localhost`)"
      - "traefik.http.routers.extract.entrypoints=websecure"
      - "traefik.http.routers.extract.tls=true"
      - "traefik.http.services.extract.loadbalancer.server.port=8082"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      extract-otp-db:
        condition: service_healthy
    env_file:
      - extract-otp/.env
    profiles: ["extract-otp", "all"]

  # -------- Redis --------
  redis:
    container_name: redis
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    profiles: ["authentication", "extract-otp", "all"]

  # -------- Auth DB --------
  auth-db:
    container_name: auth-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB?AUTH_POSTGRES_DB is required}
      POSTGRES_USER: ${AUTH_POSTGRES_USER?AUTH_POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD?AUTH_POSTGRES_PASSWORD is required}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: ["authentication", "all"]

  # -------- Extract OTP DB --------
  extract-otp-db:
    container_name: extract-otp-db
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${EXTRACT_OTP_POSTGRES_DB?EXTRACT_OTP_POSTGRES_DB is required}
      POSTGRES_USER: ${EXTRACT_OTP_POSTGRES_USER?EXTRACT_OTP_POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${EXTRACT_OTP_POSTGRES_PASSWORD?EXTRACT_OTP_POSTGRES_PASSWORD is required}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${EXTRACT_OTP_POSTGRES_USER} -d ${EXTRACT_OTP_POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: ["extract-otp", "all"]

  # -------- RabbitMQ --------
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2.0-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME?RABBITMQ_USERNAME is required}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD?RABBITMQ_PASSWORD is required}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: ["authentication", "notification", "extract-otp", "all"]
